---
title: "draft_article"
format: html
---


```{r}
library(tidymodels)
library(readmission)
library(tictoc)
library(future)
plan(multisession)

set.seed(1)
readmission_splits <- initial_split(readmission, strata = readmitted)

readmission_folds <- vfold_cv(training(readmission_splits), strata = readmitted)

recipe_basic <- recipe(readmitted ~ ., data = training(readmission_splits)) |>
  step_mutate(
    race = factor(case_when(
      !(race %in% c("Caucasian", "African American")) ~ "Other",
      .default = race
    ))
  ) |>
  step_unknown(all_nominal_predictors()) |>
  step_YeoJohnson(all_numeric_predictors()) |>
  step_normalize(all_numeric_predictors()) |>
  step_dummy(all_nominal_predictors())

spec_bt <- boost_tree(
  mode = "classification",
  trees = 500,
  mtry = tune(),
  min_n = tune(),
  learn_rate = tune(),
  tree_depth = tune()
)

bt_grid <- grid_space_filling(
  mtry(range = c(5, 20)),
  min_n(),
  learn_rate(),
  tree_depth(),
  size = 400
)
```



```{r}
tic()
local_results <- tune_grid(
  object = spec_bt,
  preprocessor = recipe_basic,
  resamples = readmission_folds,
  grid = bt_grid,
  control = control_grid(verbose = TRUE, parallel_over = "everything")
)
toc()

saveRDS(local_results, "tune/results/local_results.rds")
```

Timing: 2007.381 sec elapsed
Apple M3, 8 cores (4 performance + 4 efficiency), 24 GB RAM. 

2007.381  -- 33 mins


```{r}

cluster_id <- "0610-210321-nnvxwjl0"

repo <- "https://databricks.packagemanager.posit.co/cran/__linux__/noble/latest"

r_libs <- libraries(
  lib_cran("reticulate", repo = repo),
  lib_cran("tidymodels", repo = repo),
  lib_cran("xgboost", repo = repo),
  lib_cran("readmission", repo = repo)
)

db_libs_install(cluster_id, r_libs)

py_lib <- lib_pypi("rpy2==3.5.7") |>
  libraries()

db_libs_install(cluster_id, py_lib)

wait_for_lib_installs(cluster_id)
```


```{r}
library(sparklyr)

sc <- spark_connect(
  method = "databricks_connect", 
  cluster_id = cluster_id
  )

tic()
spark_results <- tune_grid_spark(
  sc = sc,
  object = spec_bt,
  preprocessor = recipe_basic,
  resamples = readmission_folds,
  grid = bt_grid,
  control = control_grid(verbose = TRUE, parallel_over = "everything")
)
toc()

saveRDS(spark_results, "tune/resultsspark_results.rds")
```

Timing: 1242.861 sec elapsed

1242 - 20 mins (10 concurrent)
622 - 10 (32 concurrent)

Node specs:  32 GB Memory, 8 Cores

In Workbench:

22535.651 sec elapsed

8 cores
x86_64
6hours 15 minutes
AMD EPYC 7571
2.1 GHz





