---
title: "Usando Big Data con R"
output: html_notebook
---

```{r setup,  include = FALSE}

## Librerías principales
library(data.table)
library(dtplyr)

## Librerías secundarias
library(tictoc) ## Para ver cuanto tiempo toma una sección del código
library(here) ## Para saber la dirección exacta de nustro folder de trabajo
library(fs) ## Librería que ayuda con directorios y archivos

```

## `data.table` (con `dtplyr`)

```{r}
library(data.table)
```

Para leer múltiples archivos con `data.table`, combinamos `fread()` con `rbindlist()`,
y `lapply()` para iterar por cada archivo
```{r}
tic()

datos_dt <- rbindlist(
  lapply(
    dir_ls(folder_datos),
    fread
  )
)

toc()
```

`data.table` lee 
```{r}
lobstr::obj_size(datos_dt)
```

```{r}
library(dtplyr)
```

```{r}
datos_dtp <- lazy_dt(datos_dt)
```

```{r}
lobstr::obj_size(datos_dtp, datos_dt)
```

```{r}
datos_dtp %>% 
  mutate(mes_empieza_viaje = month(tpep_pickup_datetime)) %>% 
  group_by(mes_empieza_viaje) %>% 
  summarise(
    cantidad = n(),
    promedio_de_pasajeros = mean(passenger_count)
  )
```

```{r}
datos_dtp %>% 
  mutate(mes_empieza_viaje = month(tpep_pickup_datetime)) %>% 
  group_by(mes_empieza_viaje) %>% 
  summarise(
    cantidad = n(),
    promedio_de_pasajeros = mean(passenger_count)
  ) %>% 
  as_tibble()
```

```{r}
datos_dtp %>% 
  mutate(mes_empieza_viaje = month(tpep_pickup_datetime)) %>% 
  group_by(mes_empieza_viaje) %>% 
  summarise(
    cantidad = n(),
    promedio_de_pasajeros = mean(passenger_count)
  ) %>% 
  show_query()
```

