---
format: 
  revealjs:
    smaller: true
    transition: fade
    background-transition: fade
    theme: [default, theme.scss]
    menu: false
execute: 
  eval: false
  echo: false
---

# Databricks with R {background-image="assets/title-slide-white.png"}

Edgar Ruiz @ Posit 

[linkedin.com/in/edgararuiz](https://www.linkedin.com/in/edgararuiz/)

## Spark Connect {background-image="assets/slide-frame.png"}

- Introduced a decoupled client-server architecture that allows remote
connectivity to Spark clusters using the DataFrame API. 

- The **separation will allow R users to interact with a cluster**
from the comfort of their preferred environment, laptop or otherwise.

- [Databricks
Connect](https://docs.databricks.com/dev-tools/databricks-connect.html),
available in DBR version 13 and above, is based on this
new architecture.

## Integrating R  {background-image="assets/slide-frame.png"}

- Connect, uses of a remote procedure call framework, named gRPC.  **Torch**
for the ML capabilities.

- `PySpark`, the Python library, offers the best integration with Connect.

- `sparklyr` will integrate to PySpark via the `reticulate` package.

- Extends the functionality, and user experience: `dplyr` back-end, `DBI` back-end,
RStudio's *Connections pane* integration.

## Databricks Connect (ML 13+) {background-image="assets/slide-frame.png"}

-   Your [Workspace Instance
    URL](https://docs.databricks.com/workspace/workspace-details.html#workspace-url)
-   The ID of a currently running
    [cluster](https://docs.databricks.com/workspace/workspace-details.html#cluster-url-and-id)
    within your workspace
-   Authentication setup. At this time, `sparklyr` supports
    [PAT](https://docs.databricks.com/dev-tools/auth.html#pat)
- In `spark_connect()` use `databricks_connect` as the `method` argument

``` r
library(sparklyr)

sc <- spark_connect(
 host = "[Your Workspace Instance URL]", 
 cluster_id = "[Cluster ID]"
 token = "[Your PAT - Please do not include 
          it as plain text here,  please refer 
          to the next section]"
  )
```
