---
title: "Databricks and pins"
subtitle: "Scheduled job"
format: html
---

```{r}
#| include: false
library(tidymodels)
library(tidyverse)
library(pysparklyr)
library(sparklyr)
library(pins)
```

```{r}
lending_predict <- function(local_lending) {
  library(tidymodels)
  library(tidyverse)
  library(pins)
  url_pin <- "/Volumes/sol_eng_demo_nickp/end-to-end/r-models/lending-model-linear/20250421T150450Z-321f3/lending-model-linear.rds"
  if(file.exists(url_pin)) {
    model <- readRDS(url_pin)  
  } else {
    board <- board_databricks("/Volumes/sol_eng_demo_nickp/end-to-end/r-models")
    model <- pin_read(board, "lending-model-linear")
  }
  preds <- predict(model, local_lending)
  local_lending |> 
    bind_cols(preds) |> 
    select(56, interest_rate, everything())
}

sc <- spark_connect(method = "databricks_connect", cluster_id = "0420-215537-3a6xz4zr")
tbl_lending <- tbl(sc, I("sol_eng_demo_nickp.`end-to-end`.loans_full_schema"))

with_preds <- tbl_lending |> 
  spark_apply(lending_predict) |> 
  mutate(diff = interest_rate - `_pred`) |> 
  compute()

sd_diff <- with_preds |> 
  summarise(x = sd(diff, na.rm = TRUE)) |> 
  pull()

# Downloads results to R
large_diffs <- with_preds |> 
  filter(diff > sd_diff) |> 
  collect()

# New results uploaded to a different pin
board <- board_databricks("/Volumes/sol_eng_demo_nickp/end-to-end/r-models")
pin_write(board, large_diffs, "large_differences", type = "csv")
```
